name: Bug Report
description: Something is broken
title: "Bug: "
labels: ["bug"]

body:
  - type: textarea
    attributes:
      label: What's wrong?
      placeholder: Tell us what's broken
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce
      placeholder: What did you do when this happened?
    validations:
      required: true